### ISSUE TITLE
Grabbing ID as well as fields

### ISSUE THREAD

**Issue by slawder** [Khaledgarbaya/ContentfulReactNative-boilerplate#1]
How would I grab the ID of a content row along with the fields? I can reference them in the 

> response.items.map

 function by doing something like

> post.sys.id

I can grab all of the actual post fields I want to render in a list view from **post.fields** and returning that in that particular function, but then am left without an ID to use to link to the actual content.

**Comment by slawder** [comment]
Nevermind. I was running into problems since the initial empty rows don't have data like post.sys.id, but if I check for it then get past it initially, things seem to work.

**Comment by Khaledgarbaya** [comment]
Hi @slawder sorry for the late response, Glad it worked for you.
Feel free to create an issue anytime
